/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "on-secondary-fixed": "#1b1c1c",
        "on-tertiary-fixed-variant": "#5a4045",
        "tertiary-fixed-dim": "#e3bdc4",
        "secondary-fixed-dim": "#c8c6c6",
        "on-primary-fixed": "#0f1f13",
        "on-secondary-container": "#656464",
        "on-secondary-fixed-variant": "#474747",
        "inverse-primary": "#b8ccb8",
        "surface-tint": "#516353",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface": "#f9f9f8",
        "primary-fixed-dim": "#b8ccb8",
        "error": "#ba1a1a",
        "primary": "#4f6051",
        "surface-container-highest": "#e2e2e2",
        "secondary-fixed": "#e4e2e1",
        "inverse-on-surface": "#f1f1f0",
        "outline": "#747872",
        "primary-container": "#677968",
        "secondary-container": "#e4e2e1",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary": "#71545a",
        "background": "#f9f9f8",
        "on-primary-fixed-variant": "#3a4b3c",
        "surface-bright": "#f9f9f8",
        "tertiary-fixed": "#ffd9df",
        "tertiary-container": "#8c6c72",
        "on-background": "#1a1c1c",
        "surface-container": "#eeeeed",
        "secondary": "#5f5e5e",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e8e8e7",
        "inverse-surface": "#2f3130",
        "primary-fixed": "#d4e8d4",
        "on-surface-variant": "#434843",
        "on-primary-container": "#f6fff3",
        "surface-dim": "#dadad9",
        "on-tertiary-container": "#fffbff",
        "outline-variant": "#c3c8c0",
        "surface-container-low": "#f3f4f3",
        "on-tertiary-fixed": "#2b151a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "inline-gap": "0.75rem",
        "container-padding": "2rem",
        "component-gap": "1.5rem",
        "section-gap": "4rem",
        "max-width": "860px"
      },
      fontFamily: {
        "headline-lg": ["Pretendard", "Noto Sans", "sans-serif"],
        "body-md": ["Pretendard", "Noto Sans", "sans-serif"],
        "body-lg": ["Pretendard", "Noto Sans", "sans-serif"],
        "display": ["Pretendard", "Noto Sans", "sans-serif"],
        "label-md": ["Pretendard", "Noto Sans", "sans-serif"],
        "headline-md": ["Pretendard", "Noto Sans", "sans-serif"],
        "headline-lg-mobile": ["Pretendard", "Noto Sans", "sans-serif"],
        "caption": ["Pretendard", "Noto Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "1.4", "letterSpacing": "-0.015em", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.8", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "display": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.5", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.4", "letterSpacing": "-0.015em", "fontWeight": "800" }],
        "caption": ["12px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
